export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  USER_IS_NOT_ADMIN_OF_TENANT = 'USER_IS_NOT_ADMIN_OF_TENANT',
  CREATE_USER_FAILED = 'CREATE_USER_FAILED',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  UPDATE_USER_EMAIL_NOT_ALLOWED = 'UPDATE_USER_EMAIL_NOT_ALLOWED',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_ZALO_ACCESS_TOKEN = 'INVALID_ZALO_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',

  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  CONCURRENT_MODIFICATION = 'CONCURRENT_MODIFICATION',
  INVALID_RATING = 'INVALID_RATING',

  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  INVALID_CATEGORY_PARENT = 'INVALID_CATEGORY_PARENT',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',

  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  SLOT_NOT_FOUND = 'SLOT_NOT_FOUND',
  SLOT_ALREADY_EXISTS = 'SLOT_ALREADY_EXISTS',

  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_HISTORY_NOT_FOUND = 'ORDER_HISTORY_NOT_FOUND',

  CART_IS_EMPTY = 'CART_IS_EMPTY',

  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',

  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  GET_IN_APP_NOTIFICATIONS_FAILED = 'GET_IN_APP_NOTIFICATIONS_FAILED',
  USER_CHANNEL_ALREADY_EXISTS = 'USER_CHANNEL_ALREADY_EXISTS',
  CREATE_USER_CHANNEL_FAILED = 'CREATE_USER_CHANNEL_FAILED',
  USER_CHANNEL_NOT_FOUND = 'USER_CHANNEL_NOT_FOUND',
  SHIPPING_PROVIDER_NOT_FOUND = 'SHIPPING_PROVIDER_NOT_FOUND',
  SHIPPING_METHOD_NOT_FOUND = 'SHIPPING_METHOD_NOT_FOUND',
  SHIPPING_METHOD_NOT_AVAILABLE = 'SHIPPING_METHOD_NOT_AVAILABLE',
  SHIPPING_METHOD_IS_NOT_VALID = 'SHIPPING_METHOD_IS_NOT_VALID',

  CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED',
  VOUCHER_IS_INVALID = 'VOUCHER_IS_INVALID',
  ORDER_IS_NOT_NEW = 'ORDER_IS_NOT_NEW',
  VOUCHER_IS_NOT_ASSIGNED_TO_USER = 'VOUCHER_IS_NOT_ASSIGNED_TO_USER',
  NOT_APPLICABLE_FOR_THIS_VOUCHER = 'NOT_APPLICABLE_FOR_THIS_VOUCHER',
  MINIMUM_AMOUNT_NOT_MET = 'MINIMUM_AMOUNT_NOT_MET',
  VARIANT_IS_NOT_AVAILABLE = 'VARIANT_IS_NOT_AVAILABLE',
  MIXED_CURRENCIES_NOT_ALLOWED = 'MIXED_CURRENCIES_NOT_ALLOWED',

  // sdui
  LAYOUT_ALREADY_EXISTS = 'LAYOUT_ALREADY_EXISTS',
  NO_DEFAULT_ADDRESS = 'NO_DEFAULT_ADDRESS',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',

  // organization
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',

  // event
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',

  // subscription
  SUBSCRIPTION_PACKAGE_NOT_FOUND = 'SUBSCRIPTION_PACKAGE_NOT_FOUND',
  SUBSCRIPTION_ALREADY_EXISTS = 'SUBSCRIPTION_ALREADY_EXISTS',
  SUBSCRIPTION_IS_PENDING = 'SUBSCRIPTION_IS_PENDING',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  PACKAGE_PRICING_NOT_FOUND = 'PACKAGE_PRICING_NOT_FOUND',
  CREATE_USER_SUBSCRIPTION_FAILED = 'CREATE_USER_SUBSCRIPTION_FAILED',

  // payment
  PAYMENT_VENDOR_NOT_FOUND = 'PAYMENT_VENDOR_NOT_FOUND',
  CREATE_MOMO_PAYMENT_FAILED = 'CREATE_MOMO_PAYMENT_FAILED',
  CREATE_VNPAY_PAYMENT_FAILED = 'CREATE_VNPAY_PAYMENT_FAILED',

  CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_WITH_ID_NOT_FOUND = 'CAMPAIGN_WITH_ID_NOT_FOUND',
  CAMPAIGN_TRIGGER_WITH_ID_NOT_FOUND = 'CAMPAIGN_TRIGGER_WITH_ID_NOT_FOUND',
  CAMPAIGN_TRIGGERS_WITH_TENANT_ID_NOT_FOUND = 'CAMPAIGN_TRIGGERS_WITH_TENANT_ID_NOT_FOUND',
  VOUCHER_TYPE_ID_REQUIRED = 'VOUCHER_TYPE_ID_REQUIRED',
  DEFAULT_LOYALTY_PROGRAM_NOT_FOUND = 'DEFAULT_LOYALTY_PROGRAM_NOT_FOUND',
  LOYALTY_PROGRAM_NOT_FOUND = 'LOYALTY_PROGRAM_NOT_FOUND',
  ACTIVE_LOYALTY_PROGRAM_NOT_FOUND = 'ACTIVE_LOYALTY_PROGRAM_NOT_FOUND',
  DEFAULT_LOYALTY_TIER_NOT_FOUND = 'DEFAULT_LOYALTY_TIER_NOT_FOUND',
  LOYALTY_TIER_NOT_FOUND = 'LOYALTY_TIER_NOT_FOUND',
  NEXT_LOYALTY_TIER_NOT_FOUND = 'NEXT_LOYALTY_TIER_NOT_FOUND',
  NO_LOYALTY_TIERS_FOUND = 'NO_LOYALTY_TIERS_FOUND',
  POINT_BALANCE_CREATION_FAILED = 'POINT_BALANCE_CREATION_FAILED',
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
  POINT_BALANCE_PROFILE_NOT_FOUND = 'POINT_BALANCE_PROFILE_NOT_FOUND',
  POINT_BALANCE_PROFILE_ALREADY_EXISTS = 'POINT_BALANCE_PROFILE_ALREADY_EXISTS',
  POINT_EXPIRY_RULE_NOT_FOUND = 'POINT_EXPIRY_RULE_NOT_FOUND',
  VOUCHER_TYPE_NOT_AVAILABLE_FOR_REDEMPTION = 'VOUCHER_TYPE_NOT_AVAILABLE_FOR_REDEMPTION',
  INSUFFICIENT_POINTS = 'INSUFFICIENT_POINTS',
  USER_REDEMPTION_LIMIT_REACHED = 'USER_REDEMPTION_LIMIT_REACHED',
  TOTAL_REDEMPTION_LIMIT_REACHED = 'TOTAL_REDEMPTION_LIMIT_REACHED',
  VOUCHER_ISSUE_FAILED = 'VOUCHER_ISSUE_FAILED',
  VOUCHER_WITH_ID_NOT_FOUND = 'VOUCHER_WITH_ID_NOT_FOUND',
  VOUCHER_TYPE_NOT_FOUND = 'VOUCHER_TYPE_NOT_FOUND',
  VOUCHER_IS_NOT_ACTIVE = 'VOUCHER_IS_NOT_ACTIVE',
  VOUCHER_HAS_ALREADY_BEEN_REDEEMED = 'VOUCHER_HAS_ALREADY_BEEN_REDEEMED',
  VOUCHER_IS_NOT_YET_ACTIVE = 'VOUCHER_IS_NOT_YET_ACTIVE',
  VOUCHER_HAS_EXPIRED = 'VOUCHER_HAS_EXPIRED',
  USER_IDS_CANNOT_BE_EMPTY = 'USER_IDS_CANNOT_BE_EMPTY',
  MAXIMUM_10000_USERS_PER_BATCH = 'MAXIMUM_10000_USERS_PER_BATCH',
  BULK_VOUCHER_ISSUE_FAILED = 'BULK_VOUCHER_ISSUE_FAILED',
}
