apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zma-omnichannel-consumer-kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "localhost:9092"
    - name: consumerGroup
      value: "zma-omnichannel-consumer"
    - name: authRequired
      value: "false"
